- hosts: servidores_web
  become: true
  roles:
   - role: apache2

- hosts: servidores_web
  become: true
  roles:
   - role: router

- hosts: all
  become: true
  roles:
   - role: commons

- hosts: servidores_bd
  become: true
  roles:
   - role: mariadb
