network:
  version: 2
  ethernets:
    ens3: 
      dhcp4: false
      addresses: ["192.168.201.2/24"]
    ens4: 
      dhcp4: false
      addresses: ["10.0.0.2/24"]
      routes:
        - to: default
          via: 10.0.0.1
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]